### ISSUE TITLE
[Feature] Additional Configuration that ignores linting against specific subroutines and snippets

### ISSUE THREAD

**Issue by ysugimoto** [ysugimoto/falco#273]
### Kind of proposals

- [] Parser
- [x] Linter
- [] Simulator
- [] Testing

### Describe the feature

This request comes from #272, an additional configuration that controls linting behavior - ignoring - will be helpful for *Fastly Managed* snippets.

Particularly, when the deliver service is working with NGWAF - Fastly Next-Gen Waf - then Fastly injects their managed dynamic snippets into the service.  Those snippets could not be under control by the user and may be changed in their circumstance (updating waf feature, etc).

It causes a problem that _unrecognized scope_ in falco's [understanding subroutine scope](https://github.com/ysugimoto/falco/blob/main/docs/linter.md#user-defined-subroutine) so we need to recognize scope without changing subroutine name or putting annotation comment.

To solve it, I think adding a configuration field is a good way to control them.
Here is the full proposal for adding configuration in `.falco.yaml`:

```yaml
linter:
  # Coerce scope for subroutines that cannot change the name, put annotation
  # In most cases, useful for subroutines that is specified in dynamic snippet
  - enforce_subroutine_scopes:
    [subroutine_name]:
      - pass
      - miss
  # Or, ignore linting entirely for specific subroutines
  - ignore_subroutines:
      - [subroutine_name 1]
      - [subroutine_name 2]
```
